minVersion: "0.14.0"
github:
  owner: getsentry
  repo: onpremise
releaseBranchPrefix: releases
changelogPolicy: none
artifactProvider:
  name: none
statusProvider:
  name: github
targets:
  - name: github
