FROM sentry:9.0-onbuild

LABEL io.sentry.base_version="9.0-onbuild" \
      vendor="Hypertrack, Inc" \
      maintainer="andrey@hypertrack.io"

COPY sentry.conf.hypertrack.py /etc/sentry/sentry.conf.py
