FROM sentry:9.1.1-onbuild

LABEL io.sentry.base_version="9.1.1-onbuild" \
      vendor="Hypertrack, Inc" \
      maintainer="andrey@hypertrack.io"

# Sane defaults for pip
ENV PIP_NO_CACHE_DIR off
ENV PIP_DISABLE_PIP_VERSION_CHECK on

COPY sentry.conf.hypertrack.py /etc/sentry/sentry.conf.py
COPY requirements-hypertrack.txt /tmp/requirements-hypertrack.txt

RUN set -x \
    && pip install -r /tmp/requirements-hypertrack.txt \
    && rm -f /tmp/requirements-hypertrack.txt
