# This is an example of the most basic config
# that will mimic what PgBouncer does in transaction mode with one server.

[general]
host = "0.0.0.0"
port = 5432
admin_username = "postgres"
admin_password = "sentry"

[pools.sentry.users.0]
username = "postgres"
password = "sentry"
# Should be at most POSTGRES_MAX_CONNECTIONS from .env.
pool_size = 100
# We can always eagerly load connections because pgcat will be the only client to the postgres container.
min_pool_size = 100
pool_mode = "transaction"

[pools.sentry.shards.0]
servers = [
  ["postgres", 5432, "primary"]
]
database = "postgres"
