#!/usr/bin/env bash

dc_base="$(docker compose version &> /dev/null && echo 'docker compose' || echo 'docker-compose')"
if [[ "$(basename $0)" = "install.sh"  ]]; then
  dc="$dc_base --ansi never --env-file ${_ENV}"
else
  dc="$dc_base --ansi never"
fi
dcr="$dc run --rm"

$dc version

$dc down --rmi local --remove-orphans
docker volume create --name=sentry-clickhouse
docker volume create --name=sentry-data
docker volume create --name=sentry-kafka
docker volume create --name=sentry-postgres
docker volume create --name=sentry-redis
docker volume create --name=sentry-symbolicator
docker volume create --name=sentry-zookeeper

cd relay
cp config.example.yml config.yml
rm credentials.json
cd ..

echo 'list images -----------------------------'
docker image list --all | grep relay
echo 'generate --------------------------------'
creds="$dcr -T --no-deps relay credentials"
ls -FGl relay
$creds generate --stdout 2> stderr > credentials.json.tmp
echo 'list images again -----------------------'
docker image list --all | grep relay
echo 'stderr ----------------------------------'
cat stderr
echo 'ls relay --------------------------------'
ls -FGl relay
echo 'creds show ------------------------------'
$creds show
echo 'moving ----------------------------------'
mv credentials.json.tmp relay/credentials.json
ls -FGl relay
echo 'relay/credentials.json ------------------'
cat relay/credentials.json
echo '========================================='
$creds show 
