blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://sentry.io/security/#vulnerability-disclosure
    about: Please see our guide for responsible disclosure.
