name: 🐞 Problem Report
description: Tell us about something that's not working the way you expect.
body:
  - type: input
    id: self_hosted_version
    attributes:
      label: Self-Hosted Version
      placeholder: 21.7.0 ← should look like this (check the footer)
      description: What version of self-hosted Sentry are you running?
    validations:
      required: true
  - type: input
    id: cpu_architecture
    attributes:
      label: CPU Architecture
      placeholder: x86_64 ← should look like this (docker info --format '{{.Architecture}}')
      description: What cpu architecture are you running self-hosted on?
    validations:
      required: true
  - type: input
    id: docker_version
    attributes:
      label: Docker Version
      placeholder: 20.10.16 ← should look like this (docker --version)
      description: What version of docker are you using to run self-hosted?
    validations:
      required: true
  - type: input
    id: docker_compose_version
    attributes:
      label: Docker Compose Version
      placeholder: 2.6.0 ← should look like this (docker compose --version)
      description: |
        What version of docker-compose are you using to run self-hosted?
        You need to use docker-compose --version if you are running < v2.0.0.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
      placeholder: |-
        e.g.:
        - latest install logs: `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`
        - `docker compose logs` output
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
    validations:
      required: false
