name: 🐞 Problem Report
description: Tell us about something that's not working the way you expect.
body:
  - type: input
    id: self_hosted_version
    attributes:
      label: Self-Hosted Version
      placeholder: 21.7.0 ← should look like this (check the footer)
      description: What version of self-hosted Sentry are you running?
    validations:
      required: true
  - type: input
    id: cpu_architecture
    attributes:
      label: CPU Architecture
      placeholder: x86_64 ← should look like this
      description: |
        What cpu architecture are you running self-hosted on?
        e.g: (docker info --format '{{.Architecture}}')
    validations:
      required: true
  - type: input
    id: docker_version
    attributes:
      label: Docker Version
      placeholder: 20.10.16 ← should look like this (docker --version)
      description: |
        What version of docker are you using to run self-hosted?
        e.g: (docker --version)
    validations:
      required: true
  - type: input
    id: docker_compose_version
    attributes:
      label: Docker Compose Version
      placeholder: 2.6.0 ← should look like this (docker compose version)
      description: |
        What version of docker compose are you using to run self-hosted?
        e.g: (docker compose version)
    validations:
      required: true
  - type: checkboxes
    id: machine_specification
    attributes:
      label: Machine Specification
      description: Make sure your system meets the [minimum system requirements of Sentry](https://develop.sentry.dev/self-hosted/#required-minimum-system-resources).
      options:
        - label: My system meets the minimum system requirements of Sentry
          required: true
    validations:
      required: true
  - type: input
    id: installation_type
    attributes:
      label: Installation Type
      placeholder: Fresh install / Upgrade from 24.8.0 to 25.5.1
      description: |
        Are you filing this issue for a fresh install or an upgrade?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: |
        Logs? Screenshots? Yes, please.
        e.g.:
          - latest install logs: `ls -1 sentry_install_log-*.txt | tail -1 | xargs cat`
          - `docker compose logs` output
      placeholder: |-
        e.g.:
        - logs output
    validations:
      required: true
  - type: input
    id: event_id
    attributes:
      label: Event ID
      description: |
        If you opted into sending errors to our error monitoring and the error has an event ID, enter it here!
      placeholder: c2d85058-d3b0-4d85-a509-e2ba965845d7
  - type: markdown
    attributes:
      value: |-
        ## Thanks
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.

        If you're reporting a security issue, please follow our [security policy](https://github.com/getsentry/.github/blob/main/SECURITY.md) instead.
    validations:
      required: false
