name: 📦 Release Issue
description: Start a new self-hosted Sentry release
title: Release YY.M.N
body:
  - type: textarea
    attributes:
      label: Body
      description: "Edit YY.M.N in the title and three times in the first line of the body, then submit. 👍"
      value: |
        [previous YY.M.N](https://github.com/getsentry/self-hosted/issues) | ***YY.M.N*** | [next YY.M.N](https://github.com/getsentry/self-hosted/issues)

        - [ ] Release all components (_replace items with [publish repo issue links](https://github.com/getsentry/publish/issues)_).
          - [ ] [`develop`](https://github.com/getsentry/develop/actions/workflows/prepare-release.yml)
          - [ ] [`relay`](https://github.com/getsentry/relay/actions/workflows/release_binary.yml)
          - [ ] [`sentry`](https://github.com/getsentry/sentry/actions/workflows/release.yml)
          - [ ] [`sentry-docs`](https://github.com/getsentry/sentry-docs/actions/workflows/prepare-release.yml)
          - [ ] [`snuba`](https://github.com/getsentry/snuba/actions/workflows/release.yml)
          - [ ] [`symbolicator`](https://github.com/getsentry/symbolicator/actions/workflows/release.yml)
          - [ ] [`vroom`](https://github.com/getsentry/vroom/actions/workflows/release.yaml)
        - [ ] Release self-hosted.
          - [ ] [Prepare the `self-hosted` release](https://github.com/getsentry/self-hosted/actions/workflows/release.yml) (_replace with publish issue repo link_).
          - [ ] Check to make sure the new release branch in self-hosted includes the appropriate CalVer images.
          - [ ] Accept (publish) the release.
          - [ ] Edit [release notes](https://github.com/getsentry/self-hosted/releases).
        - [ ] Follow up.
          - [ ] [Create the next release issue](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=release.yml) and link it from this one.
            - _replace with link_
          - [ ] Update the [quarterly ticket](https://github.com/getsentry/team-ospo/issues).
          - [ ] Update the [release issue template](https://github.com/getsentry/self-hosted/blob/master/.github/ISSUE_TEMPLATE/release.yml).
          - [ ] Create a PR to update relocation release tests to add the new version.
            - _replace with link_
    validations:
      required: true
