# The lockfile path should be included in the `.gitignore`.
UPGRADE_LOCKFILE=".upgrade.lock"

# Usage: `exists_in_lockfile <key>`
# Returns 1 if the key exists in the lockfile, 0 otherwise
function exist_in_lockfile {
  # Read `.upgrade.lock` file and check whether the `key` exists
  grep -q "$1" "$UPGRADE_LOCKFILE"
  return $?
}

# Usage: `add_to_lockfile <key> <key>`
# Adds the `key` to the lockfile, and mark it as executed
function add_to_lockfile {
  # If the `.upgrade.lock` file does not exist, create it
  # with warnings of "DO NOT EDIT" etc above it.
  # Otherwise, just add the `key` and the current timestamp
  # to the maching key separated by a space.
  # Example: `key 2022-01-01T00:00:00Z`
  if [[ ! -f "$UPGRADE_LOCKFILE" ]]; then
    echo "// This file is automatically generated for self-hosted Sentry installations. DO NOT EDIT." >"$UPGRADE_LOCKFILE"
  fi

  # If the `key` already exists, do nothing
  if exist_in_lockfile "$1"; then
    return
  fi

  # Add the `key` and the current timestamp to the maching key separated by a space.
  # Example: `key 2022-01-01T00:00:00Z`
  local timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z")
  echo "$1 $timestamp" >>"$UPGRADE_LOCKFILE"
}
